### ISSUE TITLE
Adds duplicates of the newly created event to event table

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_EventManagement#59] opened 2021-05-30 15:27 UTC
- Create a new event 
- Fill in the required fields and click Save
- After the navigation, refresh the page

Result: 
- The browser asks for form resubmission (Confirm Form Resubmission) If Continue clicked, a copy of the last created event will be added to the list. When the browser (Chrome browser) window is small, the browser won't ask for Confirm Form Resubmission on refresh and it will add the duplicate of the event to the list of events automatically and it will happen for each refresh on the page.

**Comment by EleonoraPetzold** [comment] 2022-04-19 11:41
The problem has not yet occurred in the running operation. I could not reproduce it either. I have tested it with firefox and chrome. 
I am closing the issue, if the problem occurs again please open it again

**Closed by EleonoraPetzold** 2022-04-19 11:41 UTC
Labels: Type: bug, Priority: Medium
