### ISSUE TITLE
Date format isn't compatible with Firefox browser

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_EventManagement#58] opened 2021-05-30 15:10 UTC
- Click create a new event 
- Fill in the required fields and click Save

Result: 
- For the calendar field, It gives the warning "The field Start date must be a date." this happens for the Firefox browser.

![err](https://user-images.githubusercontent.com/66725469/120109467-e1442b00-c169-11eb-9678-d8c35469457e.png)

**Comment by EleonoraPetzold** [comment] 2022-04-19 11:33
I can't reproduce this, in debug and production mode everything is ok:

![image](https://user-images.githubusercontent.com/42029171/163994346-712af632-0b24-425c-b091-d889d5a392eb.png)

![image](https://user-images.githubusercontent.com/42029171/163994416-4c9431f7-a19a-4c85-9ca2-9fb53b5e8144.png)

I am closing the issue, if problem occurs again please open again

**Closed by EleonoraPetzold** 2022-04-19 11:33 UTC
Labels: Type: bug, Priority: Medium
